# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20170705_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_accounts',
            name='Transactions',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='categories',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Unapproved', 'Unapproved')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='classifications',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque')], default='Cash', max_length=30),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='trans_type',
            field=models.CharField(blank=True, choices=[('in_trans', 'in_trans'), ('out_trans', 'out_trans')], max_length=20),
        ),
    ]
