# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20170705_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_accounts',
            name='balance',
            field=models.CharField(default=0, max_length=70),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='classifications',
            field=models.CharField(blank=True, choices=[('Cheque', 'Cheque'), ('Cash', 'Cash')], default='Cash', max_length=30),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='trans_type',
            field=models.CharField(blank=True, choices=[('out_trans', 'out_trans'), ('in_trans', 'in_trans')], max_length=20),
        ),
    ]
